### ISSUE TITLE
Collation error for 8-page document

### ISSUE THREAD

**Issue by dubsnipe** [jywarren/bookletize.js#1]
I tried testing an 8-page document using the [demo](https://jywarren.github.io/bookletize.js/) and found that it printed them in this order:

* Page 1: 1, 7
* Page 2: 2, 6
* Page 3: 5, 3
* Page 4: 4, 8

Once printed, the final page ended up in the middle of the booklet.

**Comment by jywarren** [comment]
oh oops! Hmm. Can you share the original? Thanks! 

It must be an error with this section of logic though I'll need to go through it carefully to test.

https://github.com/jywarren/bookletize.js/blob/c05efc8a0e594a7e2bd7825794d4d0124fec2cf8/dist/bookletize.js#L33-L55

**Comment by dubsnipe** [comment]
For sure! [Here's the document](https://drive.google.com/file/d/1ARlkBKJebtxi_sxVMcUn4k4AEEZPwiKK/view?usp=sharing).

**Comment by jywarren** [comment]
Confirmed, and here's the current output, thanks! 

[ffe72230-bb28-4082-82a3-0524e68b2e4b.pdf](https://github.com/jywarren/bookletize.js/files/6118475/ffe72230-bb28-4082-82a3-0524e68b2e4b.pdf)

Will try to figure this out...

**Comment by dubsnipe** [comment]
You caught me looking at the code! I am not good with Javascript, but I imagine it has to do with checking whether ```origPages.length``` is odd or even. If it's even, you add a page, if it's even you do not, and then collate.

**Comment by jywarren** [comment]
I believe i fixed it... can you test it out? You may need to clear your cache, which you could try doing by visiting this cache-busting URL: https://jywarren.github.io/bookletize.js/?12345

**Comment by jywarren** [comment]
I think i was pulling not the final page but the 2nd to last page, each time!

**Comment by jywarren** [comment]
Thanks for the catch!!!!
